apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-server
  namespace: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-server
  template:
    metadata:
      labels:
        app: deploy-server
    spec:
      containers:
      - name: deploy-server
        image: kkangmin2/learn-deploy:v1.0.0
        envFrom:
          - secretRef:
              name: deploy-secret
        ports:
        - containerPort: 80
