apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-server
  namespace: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-server
      db: deploy-db
  template:
    metadata:
      labels:
        app: deploy-server
        db: deploy-db
    spec:
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: deploy-pv
          persistentVolumeClaim:
            claimName: deploy-pvc
      containers:
      - name: deploy-server
        image: kkangmin2/learn-deploy-server:0.34
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: deploy-secret
        ports:
        - containerPort: 3000
      - name: deploy-db
        image: kkangmin2/learn-deploy-db:0.1
        imagePullPolicy: Always
        volumeMounts:
          - name: deploy-pv
            mountPath: "/usr/share/logs"
        envFrom:
        - secretRef:
            name: deploy-secret-pg
        ports:
        - containerPort: 5432